meetings/2016-12-22/minutes.md
Minutes for https://github.com/nodejs/security-wg/issues/6
=> doc: add minutes for Dec 22, 2016

meetings/2017-01-05/minutes.md
Fix: https://github.com/nodejs/security-wg/issues/13
=> doc: add minutes for January 5th, 2017

meetings/2016-03-02.md
=> doc: add minutes for March 2, 2017

meetings/2017-07-13.md
=> doc: add minutes for July 13th, 2017

meetings/2017-10-12.md
@nodejs/security-wg 
- Close: #52
- Close: #53
=> doc: add minutes for October 12th, 2017

README.md
I also fixed a few cosmetic markdown issues and linkified "CTC."
=> Bullet point in "responsibilities" was missing a direct object.

meetings/2017-11-02.md
I did add an **acton** for @bengl at the end -- we did not seem to note what I think I recall as an action to pull together a group membership process doc. Please confirm.
=> Nov 2 meeting minutes

processes/third_party_vuln_process.md
Following @cjihrig suggestion in order to make this delay more realistic.
=> update triage team response delay

processes/third_party_vuln_process.md
=> Add Bryce to third party triage team.

processes/third_party_vuln_process.md
=> processes: add cjihrig to ecosystem triage team

processes/third_party_vuln_process.md
As per https://github.com/nodejs/security-wg/pull/76#discussion_r156321055
=> Add @bengl to 3rd-party triage team

vuln/npm/357.json
I hope this is correct.
I think we should develop an easy-to-use tool to compile these, it's quite tedious otherwise.
=> vuln: Added CVE-2017-10910

processes/third_party_vuln_process.md
Requesting to be part of the triage team
=> Add Liran Tal to vulnerability triage team

processes/third_party_vuln_process.md
=> Fix ecosystem H1 link

processes/cve_management_process.md
Language cleanup for small typo/grammar issues.
=> doc(processes): typo cleanup

processes/third_party_vuln_process.md
=> add cvss 3 for ecosystem triage

vuln/npm/360.json, vuln/npm/361.json, vuln/npm/362.json
Add 3 vulnerabilities:
these are unpatched as maintainer failed to respond in 45 days
=> add new vulnerabilities

vuln/npm/363.json
Yest another vulnerability today
=> add serve vulnerability

vuln/npm/366.json
Passing user-controlled data to clean() leads to XSS
=> vuln(html-janitor): CVE-2017-0931 

vuln/npm/374.json
vuln(CVE-2018-3726): crud-file-server Cross-site Scripting (XSS) - Stored
=> vuln(CVE-2018-3726): crud-file-server XSS

meetings/2018-02-22.md
=> add minutes for FEB 2018 

processes/third_party_vuln_submit_form_hacker1.md
Follow-up on #130 - setting up the submit form on hacker1
Fixes requested:
=> docs(hacker1-template): submit form template

vuln/REAMDE.md
Adding a referencing system for our vulnerabilities.
WDYT @nodejs/security-wg ?
=> add basic vulnerability reference system

vuln/npm/382.json
Hope I filled this out right(?)
[ Ping maintainer of previously vulnerable project: @heyitsmeuralex, I think you might be able to ask for a CVE ID or something fancy like that(??) ] #142 
EDIT: I made some mistakes so you may wish to do a squash-and-merge 🙂
=> vuln: XSS in mrk.js

README.md
As a result of https://github.com/nodejs/security-wg/issues/140, we've created a slack org - now adding it to the README, so everyone who is interested can find it easily.
cc @nodejs/security-wg
=> feat(slack): add the join us on slack button

vuln/npm/384.json
I'm skipping 383 cause I have it on a branch ready for pub-dis next
=> vuln(CVE-2018-3713): [angular-http-server] Path Traversal

README.md
As requested in https://github.com/nodejs/security-wg/pull/155. If we need any supporting evidence of my work around security I can provide.
=> dgonzalez into the security working group

README.md
Serves as an example for copy&paste to other projects (as well as our projects regardless).
=> Security public disclosure badge on the README

processes/third_party_vuln_process.md
=> Add Marcin Hoppe to the triage team

README.md
Fixed ordering of group member names in README file
=> docs(README): update wg members ordering

vuln/npm/144.json, vuln/npm/392.json, vuln/npm/393.json
Similar to 309.
See also #182.
=> Disclose two historic Buffer memory exposure vulns

vuln/npm/393.json
_I really need to pay more attention to the details._
=> Fix NSWG-ECO-393 publish date

vuln/npm/395.json
/cc @jasnell 
Ref: https://github.com/openwhisk/openwhisk-client-js/pull/34
=> vuln: disclose openwhisk memory exposure vuln

vuln/npm/394.json
This was disclosed long ago through side channels.
=> vuln: historic mongoose memory exposure vuln

vuln/npm/373.json, vuln/npm/374.json, vuln/npm/375.json, vuln/npm/376.json, vuln/npm/377.json, vuln/npm/378.json, vuln/npm/379.json, vuln/npm/380.json, vuln/npm/381.json, vuln/npm/382.json, vuln/npm/383.json, vuln/npm/384.json, vuln/npm/385.json, vuln/npm/386.json
Those were not being parsed correctly.
=> Fix markdown lists syntax in references

vuln/npm/397.json
=> vuln: disclose mysql memory exposure vuln

vuln/npm/85.json
Refs: https://github.com/tschaub/grunt-gh-pages/commit/590f69767203d8c379fe18cded93bd5ad6cb53cb
Refs: https://github.com/tschaub/grunt-gh-pages/pull/41
=> Fix NSWG-ECO-85 affected range

processes/security_team_onboarding.md
I would like to propose this document as a supporting process that helps on-board new members to the team.
The process also introduces the concept of a *buddy*, which we can further discuss about scope and responsibilities, but I think it can be helpful for newcomers.
Would be happy to get some feedback on any other items you find relevant to address in this process @dgonzalez @MarcinHoppe since you're both fresh on it.
=> Proposal for a process supporting on-boarding new team members

meetings/2018-03-22.md
=> add 2018-03-22 minutes

tools/vuln_valid/index.js
=> Limit titles to 150 characters, with no linebreaks

meetings/2018-04-19.md
=> add minutes for 2018-04-19 meeting

tools/vuln_valid/index.js, vuln/npm/405.json, vuln/npm/406.json, vuln/npm/407.json, vuln/npm/408.json, vuln/npm/409.json, vuln/npm/410.json, vuln/npm/411.json
A few of these crept in before https://github.com/nodejs/security-wg/pull/218 was merged, and the validation in https://github.com/nodejs/security-wg/pull/219 wasn't updated for that PR. This fixes both issues.
=> Replace final few empty strings with null

README.md
Addresses https://github.com/nodejs/security-wg/issues/93#issuecomment-385496957
@mcollina was this what you had in mind?
=> docs(README): provide context for responsible security disclosure

vuln/npm/423.json
No tags so I linked to `master` path
=> vuln(NSWG-ECO-423): fs-path

vuln/npm/319.json
Refs: https://github.com/jonschlinkert/remarkable/issues/227
Anything else we should fix?
Also /cc @grnd, this should also be updated at https://snyk.io/vuln/npm:remarkable:20160820, probably.
=> fix(NSWG-ECO-319): actualize author info

vuln/npm/435.json
=> vuln(NSWG-ECO-435): react-marked-markdown

vuln/npm/428.json
=> fix(NSWG-ECO-428): update current status

README.md
This adds a CoC and a Moderation policy to the repo
=> add CoC and Moderation Policy

README.md
=> docs(guides): update links to CoC and Moderation pages

vuln/core/49.json, vuln/core/50.json, vuln/core/51.json, vuln/core/52.json
Add core vulnerability database entries for
June security release.
=> doc: add entries for June vulns

.github/CODEOWNERS
Updating paths and Node.js core triage team based on historical activity
=> chore(codeowners): update paths and core team

README.md
I'd like to nominate Andreas Tiefenthaler (@pxlpnk) to the Working Group. Andreas has been actively helping us with the vulnerability database and I believe he would be a great asset to this team.
=> Nominate Andreas Tiefenthaler to the WG

vuln/npm/450.json
Need some eyes on the report, as this is largely based off of https://github.com/eslint/eslint-scope/issues/39.
Specifically, about the author and cvss.
=> vuln(NSWG-ECO-450): eslint-scope

README.md
Fixes: https://github.com/nodejs/security-wg/issues/302
Refs: https://github.com/nodejs/security-wg/issues/313
=> doc: update membershp list after review

vuln/npm/399.json
=> vuln(NSWG-ECO-399): add cve

tools/reporter/NswgReporter.js
Aligning the nswg-reporter CLI with latest changes in report's user structure as described in https://github.com/nodejs/security-wg/pull/314
=> feat(nswg-reporter): use rich user object for reports

vuln/npm/457.json
Fixes https://github.com/nodejs/security-wg/issues/371
cc @lirantal
=> Added aedes vuln

vuln/npm/457.json
cc @mcollina cve assignment approved from H1
=> vuln(NSWG-ECO-457): add cve

README.md
Refs: https://github.com/nodejs/TSC/pull/548
Refs: https://github.com/nodejs/security-wg/issues/368
Fixes: https://github.com/nodejs/security-wg/issues/365
/cc @Trott
=> doc: sync charter with the actually approved one

processes/recognition.md
References:
* https://github.com/nodejs/security-wg/issues/293 - Acknowledging most active hackers for ecosystem #293 
* https://github.com/nodejs/security-wg/issues/311 - Schedule Tweet - Agree on text #311
cc @ZibbyKeaton for review
=> Process for recognizing work

README.md
Proposing an upgrade to the README:
- Table of Contents for easier accessibility to resources in the WG
- Adding badges for friendlier access to resources like our recorded youtube meetings, twitter handle etc 
New layout preview:
=> docs(README): toc intro and new badges

processes/responsible_disclosure_template.md, processes/third_party_vuln_process.md
Andreas (@pxlpnk) has been helping the WG with the management of our vulnerability database.
He has expressed the will to join the triage team and I believe he would be a great asset.
Please add your :+1: and LGTM :D
=> add Andreas to triage team

README.md
I'd like to re-join the sec-wg after some time off.
I was involved in the original forming of the WG, helping to import to ecosystem bug JSON, and other activities. I'm now back working full time on Node.js and have the time to participate in the WG again.
=> Request to re-join Security WG

meetings/nodejs-collab-summit/nodejs-collab-summit-vancouve-2018.md
Fixes #417 #358 
- Meeting Agenda
- Meeting Minutes
=> docs(collab-summit): vancouver collab summit 2018 

vuln/npm/477.json
Related thread: https://github.com/dominictarr/event-stream/issues/116
Package has been removed from npm.
=> nbswg-eco-477

processes/security_release_process.md
Mostly reorganize into time phases, and some text clarifications.
=> doc: minor clarifications to release process

vuln/npm/479.json
=> vuln(cvss): adjust cvss scores

vuln/npm/491.json
=> vuln(NSWG-ECO-491): mpath

vuln/npm/492.json
=> vuln(NSWG-ECO-492): just-extend

vuln/npm/494.json
=> vuln(NSWG-ECO-494): defaults-deep

vuln/npm/493.json
=> vuln(NSWG-ECO-493): lodash

processes/cve_management_process.md
Fixes: https://github.com/nodejs/TSC/issues/684
=> processes: use iojs email addresses to submit CVEs

.travis.yml
=> fix(travis): remove deprecated sudo configuration

meetings/2019-03-25.md
=> adding minutes for 2019-03-25

package-lock.json, package.json
Refs: https://nvd.nist.gov/vuln/detail/CVE-2019-10742
=> update axios to 0.19.0

processes/security_team_onboarding.md
Added further emphasis on communication of sec wg members
=> docs(process): coc review notes

processes/security_team_onboarding.md
As proposed by @cjihrig in a previous PR comment (https://github.com/nodejs/security-wg/pull/540#discussion_r291577415), I'm updating this list.
Please review to approve.
=> docs(processes): update security team members

README.md, processes/third_party_vuln_process.md
Hi @nodejs/security-wg,
Following up on @karenyavine's request to join the group (https://github.com/nodejs/security-wg/issues/545) and some +1s in that issue I would like to formalize this into the process and nominate Karen to join the Security WG working mostly on the triage team but leaving it open for her to take action in other activities.
What's next?
- Happy to get your 👍 and approval fo the PR
- I will onboard Karen to the team and processes per https://github.com/nodejs/security-wg/blob/master/processes/security_team_onboarding.md#the-buddy-program
=> chore(member): add karen yavine shemesh as new member

processes/third_party_vuln_process.md
I am on the Triage team, and I'm PRing my name in to update the list, and to indicate my acceptance of the  Triage Team policy.
=> Add Sam Roberts to ecosystem triage team

README.md
Updating the README with reference to the newly landed bug bounty criteria for H1 reports.
=> docs(readme): update bug bounty section new rewards

processes/third_party_vuln_process.md
Added myself in the members list
=> docs(processes): added karen as member

meetings/2019-07-15.md
Fixes https://github.com/nodejs/security-wg/issues/561
=> docs(meetings): agenda meeting for July

vuln/core/62.json
Covers Node.js security releases:
* 8.16.1
* 10.16.3
* 12.8.1
Ref: https://nodejs.org/en/blog/vulnerability/august-2019-security-releases/
=> vuln: vulnerabilities for Aug 2019 core releases

vuln/npm/501.json
=> vuln(NSWG-ECO-501): add cve

vuln/npm/489.json
Add CVE-2019-5484 to vulnerability
=> vuln(NSWG-ECO-489): add cve

processes/bug_bounty_criteria.md
I reached out to @arcanis to ask for his approval to add yarn to our eligible bounties and he gave his blessings ❤️
=> docs(bugbounty): add yarn as eligible for bounty

tools/vuln_valid/vulnValidate.js
The title property removed here was being immediately overwritten.
=> Remove duplicate property in tool

README.md
Changed "dislcosure" to "disclosure". :)
=> docs(readme): fix small typo in README.md

vuln/npm/400.json
@julio-Guerra  does this look ok?
=> vuln(NSWG-ECO-400): fix version range

processes/third_party_vuln_process.md
Move @cjihrig @dgonzalez @pxlpnk to emeritus status.
Related to #636 #637 #638
=> Offboard ecosystem triage team members

README.md
I'm back as a member 🎉 !
Closes https://github.com/nodejs/security-wg/issues/650
=> Add back myself as a member

README.md, processes/third_party_vuln_process.md
Adding myself to the members; fixes #657
=> Onboard Eva Sarafianou to the WG

vuln/npm/432.json
=> `id` in 432.json is wrong

.travis.yml
=> Update .travis.yml to use latest LTS

processes/bug_bounty_criteria.md
Updates the rewards information we provide for the program.
=> docs(processes): update rewards info

README.md
Adding myself to the README.md.
Issue related to my in progress nomination:
https://github.com/nodejs/security-wg/issues/678
=> chore(member): add Thomas Gentilhomme as new member

vuln/core/69.json
Signed-off-by: Michael Dawson <mdawson@devrus.com>
=> vunl: add vulns for Nov 2020 security release

package-lock.json, package.json
Update jest to latest version. Move it to dev dependencies.
=> chore: update jest

vuln/core/70.json, vuln/core/71.json, vuln/core/72.json
Signed-off-by: Michael Dawson <mdawson@devrus.com>
=> doc: add vulns for Jan 2021 security release

vuln/npm/508.json
According to 
- https://www.npmjs.com/advisories/1432
- https://github.com/advisories/GHSA-884p-74jh-xrg2
=> vuln(NSWG-ECO-508): fix vulnerable/fixed versions

vuln/core/79.json
This commit adds machine readable json for the second security release
July 2021.
=> doc: add vuln for Jul 2021 security release (2)

vuln/core/84.json, vuln/core/85.json, vuln/core/86.json
Signed-off-by: Michael Dawson <mdawson@devrus.com>
=> doc: add vulns for aug security release

vuln/core/86.json
The current JSON is broken and cannot be parsed.
=> vuln: fix broken JSON

package-lock.json, package.json
This will resolve the follow-redirects dependency issue.
=> chore: bump axios from 0.21.3 to 0.21.4

meetings/2022-05-12.md
=> doc: add meeting minutes for 05th May 2022

meetings/2022-05-26.md
Fixes: https://github.com/nodejs/security-wg/issues/798
=> doc: add meeting minutes for 26th May 2022

meetings/2022-06-02.md
=> doc: add meeting minutes to 2022-06-02

meetings/2022-06-23.md
=> doc: add meeting minutes 2022-06-23

vuln/core/94.json, vuln/core/95.json, vuln/core/96.json, vuln/core/97.json, vuln/core/98.json, vuln/core/99.json
Signed-off-by: Matteo Collina <hello@matteocollina.com>
=> Added Node.js July 2022 vulnerabilities

meetings/2022-07-07.md
=> doc: add meeting minutes 2022-07-07

meetings/2022-07-21.md
Fixes: #813
cc: @naugtur @UlisesGascon @mhdawson @facutuesca @fraxken
=> doc: include minutes 2022-07-21

meetings/2022-08-04.md
=> doc: add minutes 2022-08-04

meetings/2022-09-01.md
=> doc: add minutes 2022-09-01

README.md
Fix README due to confirming OpenJS Foundation slack here: https://github.com/nodejs/security-wg/issues/812
=> docs: update the slack invite for the openjs foundation

meetings/2022-09-15.md
Fixes: https://github.com/nodejs/security-wg/issues/833
=> doc: include meeting note 2022-09-15

meetings/2022-10-27.md
=> doc: include meeting minutes for 2022-10-27

meetings/2022-11-10.md
=> doc: add meeting minutes for 2022-11-10

meetings/2022-11-24.md
=> doc: add minutes to 2022-11-24

meetings/2022-12-08.md
=> doc: include meeting minutes 2022-12-08

meetings/2023-01-05.md
=> doc: add minutes 2023-05-01

README.md
=> doc: include 2023 initiatives

meetings/2023-01-19.md
Fixes: #862 
Co-authored-by: Ulises Gascon <UlisesGascon@users.noreply.github.com>
=> doc: add meeting minutes 19-01

vuln/core/102.json
=> doc: fix patched semver check

meetings/2023-02-02.md
Fixes: #872 
Signed-off-by: RafaelGSS <rafael.nunu@hotmail.com>
Co-authored-by: Ulises Gascon <UlisesGascon@users.noreply.github.com>
=> doc: add meeting minutes 2023-02-02

.github/workflows/stale.yml, .github/workflows/update-core-index.yml, .github/workflows/update-npm-index.yml, .github/workflows/validate-vulnerability.yml
Fixes: https://github.com/nodejs/security-wg/issues/884
=> workflow: pin dependencies by commit-hash

meetings/2023-03-16.md
=> doc: add meeting update 2023-03-16

.github/workflows/update-core-index.yml, .github/workflows/update-npm-index.yml, .github/workflows/validate-vulnerability.yml
Should use the lockfile for the CI runs
=> ci: Use npm ci to install

tools/create_index/index_generator.js, vuln/core/index.json
Opening as a draft as you'll notice the NPM index is now empty. Doesn't seem related to this change, and I can rebase it out if you'd like to land the NPM part for now
=> chore: write index files with indented format

README.md
refs: https://github.com/nodejs/security-wg/issues/923
=> meta: add marco-ippolito to the team

package-lock.json, package.json, tools/create_index/index_generator.js
Hey @RafaelGSS! 
Here's my pull request: I added some fallback values in case of something happening to the library, but maybe it's stupid because they're still hardcoded, let me know and I will change it!
=> Tools: avoid hardcode node.js versions

meetings/2023-03-30.md
=> docs: added meeting notes for 2023-03-30

meetings/2023-04-13.md
Fixes https://github.com/nodejs/security-wg/issues/945
=> doc: add meeting minutes 2023-04-13

meetings/2023-04-27
Close: https://github.com/nodejs/security-wg/issues/961
=> Added meeting minutes 2023-04-13

processes/wg_offboarding.md
In the same step, I would like to offboard myself from the WG.
=> Remove mentions of the triage team

README.md
=> doc: update current initiative champion and link

meetings/2023-05-11.md
=> docs: added meeting minutes 2023-05-11

README.md
Please also revoke relevant access.
=> Offboard Daniel Ruf

.github/workflows/test.yml
See: https://github.com/nodejs/release#release-schedule
=> Upgraded Node.js version Matrix

.github/workflows/ossf-scorecard-reporting.yml, .github/workflows/update-core-index.yml, .github/workflows/update-npm-index.yml
Allow pipelines to update previously open PR
Related to https://github.com/nodejs/security-wg/pull/999#issuecomment-1559245465
=> Improve pipelines

README.md
=> doc: add Ashish to current project members

tools/ossf_best_practices/passing_criteria.md
Related #953
This pull request contains a dump of the current [questions and answers](https://bestpractices.coreinfrastructure.org/en/projects/29) for the Node.js project in OpenSSF Best Practices for **Entry Level**. The purpose is to review the current answers, update and comment on them until we have a final version, and then update the OpenSSF Best Practices site.
=> CII-Best-Practices for Nodejs: Entry level

meetings/2023-06-08.md
=> doc: add minutes 08-06-23

meetings/2023-06-22.md
Fixes https://github.com/nodejs/security-wg/issues/1026
=> doc: add meeting minutes 22-06

meetings/2023-07-20.md
=> Added meeting minutes for 2023-07-20

README.md
=> doc: update README WG -> Team

tools/ossf_best_practices/silver_criteria.md
Related https://github.com/nodejs/security-wg/issues/953
This pull request contains a dump of the current [questions and answers](https://bestpractices.coreinfrastructure.org/en/projects/29?criteria_level=1) for the Node.js project in OpenSSF Best Practices for **Silver Level**. The purpose is to review the current answers, update and comment on them until we have a final version, and then update the OpenSSF Best Practices site.
=> CII-Best-Practices for Nodejs: Silver level

meetings/2023-08-31.md
Fixes: https://github.com/nodejs/security-wg/issues/1085
=> doc: add meeting minutes 2023-08-31

meetings/2023-09-14.md
fixes: https://github.com/nodejs/security-wg/issues/1100
=> doc: add meeting minutes 2023-09-14

meetings/2023-09-28.md
fixes: https://github.com/nodejs/security-wg/issues/1118
=> doc: add meeting minutes 2023-09-28

meetings/2023-10-26.md
=> doc: add 2023-10-26 meeting

meetings/2023-11-23.md
=> doc: add meeting minutes 2023-11-23

meetings/2023-12-21.md
=> doc: add meeting notes 2023-12-21

tools/ossf_best_practices/passing_criteria.md
- Extend and consolidate the context from #954
- Related to https://github.com/nodejs/security-wg/issues/953
=> Improve CII context for entry level

meetings/2024-01-04.md
Fixes: #https://github.com/nodejs/security-wg/issues/1175
=> doc: add 2024-01-04 notes

.github/workflows/ossf-scorecard-reporting.yml
This version won't require any change in the current pipelines. 
Note: I will re-run the pipeline after this is merged just to ensure that is working as expected 👍
=> Upgrade to openssf-scorecard-monitor@v2.0.0-beta7

meetings/2024-01-18.md
=> doc: add 2024-01-18 meeting

meetings/2024-02-01.md
fixes: https://github.com/nodejs/security-wg/issues/1214
=> doc: add 2024-02-01 minute

meetings/2024-02-29.md
fixes: https://github.com/nodejs/security-wg/issues/1237
=> doc: add 2024-02-29 minutes

README.md
=> doc: update current initiatives and remove concluded

meetings/2024-03-14.md
=> doc: add 2024-03-14 meeting notes

meetings/2024-03-28.md
Fixes: https://github.com/nodejs/security-wg/issues/1260
=> chore: add minutes doc for 2024-03-28 meeting

processes/wg_onboarding.md
This PR updates the language of the onboarding file to use gender-neutral terms, as described in the NodeJS documentation guidelines.
=> doc: use gender neutral terms

meetings/2024-04-25.md
Fixes: https://github.com/nodejs/security-wg/issues/1286
=> doc: add 2024-04-25 meeting notes

README.md
=> doc: mark Permission Model as completed

meetings/2024-05-09.md
Fixes: https://github.com/nodejs/security-wg/issues/1302
=> doc: add 2024-05-09 meeting notes

README.md
=> doc: add 2024 initiatives

meetings/2024-06-06.md
closes https://github.com/nodejs/security-wg/issues/1322
=> doc: add 2024-06-06 meeting notes

meetings/2024-06-20.md
Fixes: https://github.com/nodejs/security-wg/issues/1332
=> doc: add 2024-06-20 notes

.github/workflows/ossf-scorecard-reporting.yml
For additional context, check https://github.com/ossf/scorecard-monitor/issues/79
=> Update scorecard monitor version

meetings/2024-07-18.md
Fixes: https://github.com/nodejs/security-wg/issues/1348
=> doc: add 2024-07-18

meetings/2024-08-01.md
Fixes: https://github.com/nodejs/security-wg/issues/1355
=> doc: add august 1st meeting notes

meetings/2024-08-29.md
=> doc: add 2024-08-29 meeting notes

meetings/2024-09-12.md
Fixes: https://github.com/nodejs/security-wg/issues/1375
=> doc: add 2024-09-12 meeting notes

meetings/2024-09-26.md
Fixes: https://github.com/nodejs/security-wg/issues/1382
=> doc: add meeting note 2024-09-26

meetings/2024-10-10.md
Fixes: https://github.com/nodejs/security-wg/issues/1389
=> doc: add 10-10-2024 meeting notes

meetings/2024-11-21.md
=> Meeting notes for 2024-11-21

meetings/2024-12-05.md
Fixes: https://github.com/nodejs/security-wg/issues/1407
=> doc: add 2024-12-05 meeting notes

meetings/2024-12-19.md
Fixes: https://github.com/nodejs/security-wg/issues/1415
=> doc: add 2024-12-19 meeting notes

meetings/2025-01-30.md
Fixes: https://github.com/nodejs/security-wg/issues/1431
=> doc: add 2025-01-30 minutes

MAINTAINERS_THREAT_MODEL.md
=> doc: add nodejs.org to resource list

meetings/2025-02-27.md
=> doc: add 2025-02-27 minutes

meetings/2025-03-13.md
Fixes: https://github.com/nodejs/security-wg/issues/1444
=> doc: add 2025-03-13 meeting notes

MAINTAINERS_THREAT_MODEL.md
=> doc: add Slack and Calendar to list of resources

.github/workflows/ossf-scorecard-reporting.yml
closes https://github.com/nodejs/security-wg/issues/1456
=> feat: add pkgjs to the ossf scorecard monitor

meetings/2025-03-27.md
Fixes: https://github.com/nodejs/security-wg/issues/1460
=> doc: add 2025-03-27 meeting minutes
